### ISSUE TITLE
Cabal reports dph-seq, dph-par as deprecated.

### ISSUE THREAD

**Issue by jpt4** [wizardsportz/invertible-syntax#1]
For the record.

**Comment by gavwhela** [comment]
I suppose we may fix this... this is a fork of a very academic package with a very semantically clean and concise design. The reason for the fork however was to hack in additional primitives for increased parsing performance, so it's questionable if we want to put much time into maintaining it's cleanness.

**Comment by jpt4** [comment]
Again, submitted for the record. I don't know the lifecycle of deprecated cabal packages, and whether they might disappear from the official repositories in the future, requiring you to fork and host them privately.
